[platformio]
default_envs = esp32dev
src_dir = examples/JBWopr_Firmware
lib_dir = .

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
board_build.partitions = huge_app.csv
lib_deps =
    bblanchon/ArduinoJson @ ^7.4.1
    adafruit/Adafruit GFX Library @ ^1.12.1
    adafruit/Adafruit BusIO @ ^1.17.4
    adafruit/Adafruit LED Backpack Library @ ^1.5.0
    adafruit/Adafruit NeoPixel @ ^1.15.1
    mathertel/OneButton @ ^2.6.1
    knolleary/PubSubClient @ ^2.8.0
    https://github.com/tzapu/WiFiManager.git # WiFiManager @ ^2.0.1
    https://github.com/jonnybergdahl/Arduino_JBLogger_Library.git # JBLogger @ ^1.0.6
build_flags =
    -I src
    -Wall
    -Wextra
    -D ARDUINO_TINYS3
