//
// Created by Jonny Bergdahl on 2023-11-09.
//

#ifndef ARDUINO_WOPR_SECRETS_H
#define ARDUINO_WOPR_SECRETS_H

#define WIFI_SSID "PUT SSID HERE";
#define WIFI_PASSWORD "PUT PASSWORD HERE";

#endif //ARDUINO_WOPR_SECRETS_H
